### ISSUE TITLE
Redmine 5.01

### ISSUE THREAD

**Issue by Interfud** [nanego/redmine_additional_filters#2]
Error ID:
afd39275
Details:
Web application could not be started by the Phusion Passenger(R) application server.

Please read [the Passenger log file](https://www.phusionpassenger.com/library/admin/log_file/) (search for the Error ID) to find the details of the error.

You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Phusion Passenger(R) is run with environment set to development and/or with the friendly error pages option set to on.

**Comment by nanego** [comment]
The plugin is now updated to support Redmine 5.
